//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileSearchProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int SearchResultsID { get; set; }
        public int SearchQueryID { get; set; }
        public string FullFilePath { get; set; }
    
        public virtual SearchQuery SearchQuery { get; set; }
    }
}
